FROM jenkins/jenkins:lts-alpine

ARG SRC_URL="https://golang.org/dl/go1.17.6.linux-amd64.tar.gz"
ARG SRC_FILE="golang.tgz"

USER root

RUN curl -L ${SRC_URL} -o /opt/${SRC_FILE} && \
    tar -xzf /opt/${SRC_FILE} -C /opt && \
    rm -vf /opt/${SRC_FILE} && \
    ln -s /opt/go/bin/go /usr/bin/go && \
    ln -s /opt/go/bin/gofmt /usr/bin/gofmt

USER jenkins
