{
 "title": "k8s-pods-info",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "ns",
    "label": "NS",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$node\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$node\", namespace=~\"$ns\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nodes info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU cores usage of nodes per 2m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[2m])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage of nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name!=\"\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running pods of node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} * on(pod, namespace) group_left(node) kube_pod_info) by(node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pods capacity of node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"}) by(node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Pod info: $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "pod" },
  {
   "title": "CPU usage of container per 2m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{unit=\"core\"} * on(node) group_left() kube_pod_info{node=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\"}) by(node)",
     "legendFormat": "Total of node"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\", container!~\"^$|POD\"}[2m])) by(container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory usage of container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{unit=\"byte\"} * on(node) group_left() kube_pod_info{node=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\"}) by(node)",
     "legendFormat": "Total of node"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{instance=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\", container!~\"^$|POD\"}) by(container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU request of container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\", resource=\"cpu\"}) by(container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory request of container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\", resource=\"memory\"}) by(container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU limit of container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\", resource=\"cpu\"}) by(container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory limit of container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\", resource=\"memory\"}) by(container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Disk usage of pod per 2m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{instance=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\"}[2m])) by(device)",
     "legendFormat": "Read: {{device}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\"}[2m])) by(device)",
     "legendFormat": "Write: {{device}}"
    }
   ]
  },
  {
   "title": "Network usage of pod per 2m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\", interface=~\"(eth|enp).*\"}[2m])) by(interface)",
     "legendFormat": "RX: {{interface}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$node\", namespace=~\"$ns\", pod=~\"$pod\", interface=~\"(eth|enp).*\"}[2m])) by(interface)",
     "legendFormat": "TX: {{interface}}"
    }
   ]
  },
  {
   "title": "Total restarts of container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$ns\", pod=~\"$pod\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Status of Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$ns\", pod=~\"$pod\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "General info of pod",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$ns\", pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General info of container",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=~\"$ns\", pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}