local-address=0.0.0.0
allow-from=172.30.0.0/23,192.168.55.0/24,192.168.56.0/24
#forward-zones-recurse=.=1.1.1.1;8.8.8.8
lua-dns-script=/etc/powerdns/recursor.lua

loglevel=3
webserver=yes
webserver-address=0.0.0.0
webserver-port=8082
