services:
  pdns-recursor:
    image: "powerdns/pdns-recursor-51:latest"
    restart: "unless-stopped"
    container_name: "pdns.docker.localhost"
    network_mode: "host"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8082:8082/tcp"
    volumes:
      - "./config/recursor.conf:/etc/powerdns/recursor.conf:ro"
      - "./scripts/recursor.lua:/etc/powerdns/recursor.lua:ro"
      - "./scripts/static.txt:/etc/powerdns/scripts/static.txt:ro"
      - "./scripts/blocked.txt:/etc/powerdns/scripts/blocked.txt:ro"
