networks:
  core_network:
    name: "core_network"
    ipam:
      config:
        - subnet: "172.30.0.0/23"
          ip_range: "172.30.0.0/23"
          gateway: "172.30.1.254"

services:
  traefik:
    image: "traefik:v2.11.46"
    restart: "always"
    container_name: "traefik.docker.localhost"
    networks:
      core_network:
        ipv4_address: "172.30.1.252"
    volumes:
      - "$PWD/traefik:/etc/traefik:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80/tcp"
      - "9090:9090/tcp"
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=9090"

  powerdns:
    image: "powerdns/pdns-recursor-51:latest"
    restart: "always"
    container_name: "pdns.docker.localhost"
    networks:
     core_network:
       ipv4_address: "172.30.1.253"
    volumes:
      - "$PWD/pdns/config/recursor.conf:/etc/powerdns/recursor.conf:ro"
      - "$PWD/pdns/scripts/recursor.lua:/etc/powerdns/recursor.lua:ro"
      - "$PWD/pdns/scripts/static.txt:/etc/powerdns/scripts/static.txt:ro"
      - "$PWD/pdns/scripts/blocked.txt:/etc/powerdns/scripts/blocked.txt:ro"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8082:8082/tcp"
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=8082"
